# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: creative.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63reative.proto\x12\x03Ord\"\xc5\x03\n\tTCreative\x12\x33\n\x12\x45xternalCampaignId\x18\x01 \x01(\tH\x00R\x12\x65xternalCampaignId\x88\x01\x01\x12#\n\nExternalId\x18\x02 \x01(\tH\x01R\nexternalId\x88\x01\x01\x12\x17\n\x04Type\x18\x03 \x01(\tH\x02R\x04type\x88\x01\x01\x12\x15\n\x03Url\x18\x04 \x01(\tH\x03R\x03url\x88\x01\x01\x12\x1f\n\x08\x43\x61tegory\x18\x05 \x01(\tH\x04R\x08\x63\x61tegory\x88\x01\x01\x12\x45\n\x0c\x43reativeData\x18\x06 \x01(\x0b\x32\x1c.Ord.TCreative.TCreativeDataH\x05R\x0c\x63reativeData\x88\x01\x01\x1aq\n\rTCreativeData\x12\x1a\n\x08MediaUrl\x18\x01 \x03(\tR\x08mediaUrl\x12\x1a\n\x08TextData\x18\x02 \x03(\tR\x08textData\x12(\n\x0fTargetingRegion\x18\x03 \x03(\tR\x0ftargetingRegionB\x15\n\x13_ExternalCampaignIdB\r\n\x0b_ExternalIdB\x07\n\x05_TypeB\x06\n\x04_UrlB\x0b\n\t_CategoryB\x0f\n\r_CreativeDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'creative_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TCREATIVE._serialized_start=24
  _TCREATIVE._serialized_end=477
  _TCREATIVE_TCREATIVEDATA._serialized_start=279
  _TCREATIVE_TCREATIVEDATA._serialized_end=392
# @@protoc_insertion_point(module_scope)
