# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btoken.proto\x12\x03Ord\"\xc8\x01\n\x06TToken\x12\x0c\n\x04Hash\x18\x01 \x01(\x04\x12\x1f\n\x12\x45xternalCampaignId\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x12\n\nExternalId\x18\x03 \x01(\x04\x12\x11\n\x04Time\x18\x04 \x01(\x04H\x01\x88\x01\x01\x12(\n\x1bSomeOtherDataIfThereIsANeed\x18\x64 \x01(\tH\x02\x88\x01\x01\x42\x15\n\x13_ExternalCampaignIdB\x07\n\x05_TimeB\x1e\n\x1c_SomeOtherDataIfThereIsANeedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TTOKEN._serialized_start=21
  _TTOKEN._serialized_end=221
# @@protoc_insertion_point(module_scope)
